version: "3.8"
services:
  server:
    build:
      context: ./server/
    ports:
      - "5000:5000"
    volumes:
        - data:/data
  client:
    build:
      context: ./microservice/
    ports:
      - "5001:5001"

volumes:
    data:
